### PR TITLE
Upgrade pydata theme

### LINKED ISSUE #19: Fix CI warning on release
Message:

> Unexpected input(s) 'single-commit', valid inputs are ['SSH', 'ACCESS_TOKEN', 'GITHUB_TOKEN', 'BRANCH', 'FOLDER', 'TARGET_FOLDER', 'BASE_BRANCH', 'COMMIT_MESSAGE', 'CLEAN', 'CLEAN_EXCLUDE', 'GIT_CONFIG_NAME', 'GIT_CONFIG_EMAIL', 'REPOSITORY_NAME', 'WORKSPACE', 'SINGLE_COMMIT', 'LFS', 'SILENT', 'PRESERVE']

### PR DESCRIPTION
**Pull request by akaszynski**
Latest `pydata-sphinx-theme` has a new build process and it's a good chance for us to switch over to `pyproject.toml`.

Would like someone a bit more familiar than me with NodeJS/web development to take a look at how we can inherit better from the PyData Sphinx Theme as I've effectively just copied the files over and I think there's a better way of doing this.

Resolves #19 and #15.

### CODE REVIEW

**Review by da1910 — CHANGES_REQUESTED** [review]
Users cannot checkout the repository on Windows at the moment, because the __version__.py file has been renamed to " ." which is an invalid filename under NTFS

**Comment by akaszynski** [comment]
> Users cannot checkout the repository on Windows at the moment, because the **version**.py file has been renamed to " ." which is an invalid filename under NTFS

Crap. That’s my fault. Was testing something and should have not committed.

**Comment by akaszynski** [comment]
@da1910, removed and ready for you to take a look.

**Comment by greschd** [comment]
Fonts appear off to me, both locally built and looking at the CI artifact. Especially noticeable in the "Attributes":

image

For comparison, the currently deployed version (probably ``main``):
image

**Comment by greschd** [comment]
> Would like someone a bit more familiar than me with NodeJS/web development 

Yeah, that disqualifies me 😅

**Comment by akaszynski** [comment]
Closing this until we can figure out styling.

**Pull request closed without merging**
